language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:  
  include:
    - stage: "Test"
      name: "Unit Tests"
      script: npm test
    - stage: "Lint"
      name: "Lint"
      script: npm run lint
    - stage: "Build"
      name: "Build"
      script: npm run build