language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:  
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm test
    - script: npm run lint   
      name: "Syntax Linting"
    - script: npm install codecov -g && npm run coverage && codecov -f coverage/*.json
      name: Code Coverage