export enum NiftyStatus {
    SUBMITTING,
    ACCEPTED,
    REJECTED,
    QUEUED,
    UPLOADING,
    PENDING_RETRY,
    SUCCEEDED_UPLOADING,
    FAILED_UPLOADING,
    CANCELED,
    FINALIZING,
    SUCCEEDED,
    FAILED,
    DELETING,
    DELETED,
    DELETE_FAILED
}
