export enum NiftyStatus {
    ADDED,
    PROCESSING,
    ACCEPTED,
    REJECTED,
    QUEUED,
    UPLOADING,
    PENDING_RETRY,
    SUCCEEDED_UPLOADING,
    FAILED_UPLOADING,
    CANCELED,
    FINALIZING,
    SUCCESSFULLY_COMPLETED,
    UNSUCCESSFULLY_COMPLETED
}
